sudo: false
language: cpp
compiler:
    - clang
    - gcc
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - clang
script: make distcheck
