language: c
before_install:
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install:
    - sudo apt-get install libXxf86vm-dev cmake libsdl2-dev gcc-6
    - sudo rm /usr/bin/gcc
    - sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
    - wget --no-check-certificate https://www.lua.org/ftp/lua-5.3.3.tar.gz
    - tar zxpvf lua-5.3.3.tar.gz
    - pushd lua-5.3.3 && make linux && sudo make install && popd
compiler:
    - clang
    - gcc
script: make test
