language: c
before_install:
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo apt-get update -qq
install:
    - sudo apt-get install libXxf86vm-dev cmake libsdl2-dev
    - wget https://www.lua.org/ftp/lua-5.3.3.tar.gz
    - tar zxpvf lua-5.3.3.tar.gz
    - pushd lua-5.3.3 && make linux && sudo make install && popd
compiler:
    - clang
    - gcc
script: make test
