language: cpp
before_install:
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install:
    - sudo apt-get install libXxf86vm-dev cmake libsdl2-dev g++-6
    - sudo rm /usr/bin/g++
    - sudo ln -s /usr/bin/g++-6 /usr/bin/g++
compiler:
    - clang++
    - g++ 
script: make distcheck
