language: c
before_install:
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo apt-get update -qq
install:
    - sudo apt-get install libXxf86vm-dev cmake libsdl2-dev lua5.3 liblua5.3-0
compiler:
    - clang
    - gcc
script: make test
