sudo: false
language: cpp
compiler:
    - clang
    - gcc
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
        packages:
            - g++-6
            - clang-3.8
script: make distcheck
